In [168]:
import pandas as pd
import ast
import numpy as np

In [180]:
df_ = pd.read_csv('../datos/preprocesados/df.csv')
df_matriz = pd.read_csv('../datos/preprocesados/df_matriz.csv')

df_.head(50)

imagen  vel alambre  flujo gas  \
0   Cordon11_Seccion 1 horizontal C11.jpg          5.0        5.0   
1   Cordon12_Seccion 1 horizontal C12.jpg          4.0        4.0   
2   Cordon17_Seccion 1 horizontal C17.jpg          4.0        4.0   
3     Cordon8_Seccion 1 horizontal C8.jpg          2.0        2.0   
4     Cordon3_Seccion 1 horizontal C3.jpg          3.0        3.0   
5   Cordon19_Seccion 1 horizontal C19.jpg          5.0        5.0   
6     Cordon9_Seccion 1 horizontal C9.jpg          2.0        2.0   
7     Cordon6_Seccion 1 horizontal C6.jpg          2.0        2.0   
8     Cordon4_Seccion 1 horizontal C4.jpg          3.0        3.0   
9   Cordon10_Seccion 1 horizontal C10.jpg          5.0        5.0   
10    Cordon5_Seccion 1 horizontal C5.jpg          5.0        5.0   
11  Cordon18_Seccion 2 horizontal C18.jpg          4.0        4.0   
12    Cordon1_Seccion 1 horizontal C1.jpg          3.0        3.0   
13  Cordon13_Seccion 1 horizontal C13.jpg          4.0        4.0   
14  Cordon16_Seccion 1 horizontal C16.jpg          4.0        4.0   
15    Cordon7_Seccion 1 horizontal C7.jpg          3.0        3.0   
16    Cordon2_Seccion 1 horizontal C2.jpg          3.0        3.0   
17  Cordon14_Seccion 1 horizontal C14.jpg          4.0        4.0   
18    Cordon1_Seccion 3 horizontal C1.jpg          3.0        3.0   
19    Cordon6_Seccion 4 horizontal C6.jpg          2.0        2.0   
20  Cordon18_Seccion 3 horizontal C18.jpg          4.0        4.0   
21  Cordon13_Seccion 3 horizontal C13.jpg          4.0        4.0   
22  Cordon19_Seccion 4 horizontal C19.jpg          5.0        5.0   
23  Cordon11_Seccion 3 horizontal C11.jpg          5.0        5.0   
24  Cordon10_Seccion 3 horizontal C10.jpg          5.0        5.0   
25    Cordon7_Seccion 2 horizontal C7.jpg          3.0        3.0   
26  Cordon16_Seccion 3 horizontal C16.jpg          4.0        4.0   
27    Cordon4_Seccion 3 horizontal C4.jpg          3.0        3.0   
28  Cordon12_Seccion 3 horizontal C12.jpg          4.0        4.0   
29    Cordon3_Seccion 3 horizontal C3.jpg          3.0        3.0   
30  Cordon17_Seccion 2 horizontal C17.jpg          4.0        4.0   
31    Cordon5_Seccion 4 horizontal C5.jpg          5.0        5.0   
32  Cordon14_Seccion 3 horizontal C14.jpg          4.0        4.0   
33    Cordon2_Seccion 3 horizontal C2.jpg          3.0        3.0   
34       Cordon9_Seccion 4 horizontal.jpg          2.0        2.0   
35    Cordon8_Seccion 5 horizontal C8.jpg          2.0        2.0   
36    Cordon8_Seccion 6 horizontal C8.jpg          2.0        2.0   
37    Cordon2_Seccion 4 horizontal C2.jpg          3.0        3.0   
38  Cordon11_Seccion 4 horizontal C11.jpg          5.0        5.0   
39  Cordon12_Seccion 5 horizontal C12.jpg          4.0        4.0   
40    Cordon6_Seccion 6 horizontal C6.jpg          2.0        2.0   
41    Cordon7_Seccion 3 horizontal C7.jpg          3.0        3.0   
42  Cordon10_Seccion 4 horizontal C10.jpg          5.0        5.0   
43  Cordon18_Seccion 4 horizontal C18.jpg          4.0        4.0   
44  Cordon16_Seccion 5 horizontal C16.jpg          4.0        4.0   
45    Cordon4_Seccion 4 horizontal C4.jpg          3.0        3.0   
46    Cordon5_Seccion 7 horizontal C5.jpg          5.0        5.0   
47    Cordon9_Seccion 6 horizontal C9.jpg          2.0        2.0   
48    Cordon1_Seccion 5 horizontal C1.jpg          3.0        3.0   
49  Cordon14_Seccion 4 horizontal C14.jpg          4.0        4.0   

    peri voltaje  voltaje  corriente  ubicacion     pixeles  mm_por_pixel  \
0            5.0      5.0        5.0          1  196.002551     65.334184   
1            4.0      4.0        4.0          1  197.002538     65.667513   
2            4.0      4.0        4.0          1  176.002841     58.667614   
3            2.0      2.0        2.0          1   95.005263     31.668421   
4            3.0      3.0        3.0          1  128.003906     42.667969   
5            5.0      5.0        5.0          1  182.

In [170]:
def safe_eval(item):
    try:
        return ast.literal_eval(item)
    except (ValueError, SyntaxError) as e:
        print(f"Error al evaluar: {e} - Item: {item}")
        return None 


In [171]:

def convert_to_float32(matrix):
    if matrix is None:
        return None
    return np.array(matrix, dtype=np.float32)

In [172]:
df_matriz['matriz'] = df_matriz['matriz'].apply(lambda x: convert_to_float32(safe_eval(x)))

In [173]:
print(df_matriz.dtypes)  # Para verificar los tipos de datos de las columnas

# Verificar los primeros elementos de la columna 'matriz'
print(df_matriz['matriz'].head())

# Verificar el contenido de una celda específica
print(df_matriz['matriz'].iloc[0]) 

imagen    object
matriz    object
dtype: object
0    [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], [1....
1    [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], [1....
2    [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], [1....
3    [[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0....
4    [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], [1....
Name: matriz, dtype: object
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [174]:
for matriz in df_matriz['matriz']:
    print(type(matriz), matriz.dtype) 

<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class 'numpy.ndarray'> float32
<class '

In [175]:
df_final = pd.merge(df_, df_matriz, on='imagen', how='inner')
df_final.head()
# Guardar dataframe final
df_final.to_csv('../datos/df_final.csv', index=False)

In [176]:
df_final

imagen  vel alambre  flujo gas  \
0   Cordon11_Seccion 1 horizontal C11.jpg          5.0        5.0   
1   Cordon12_Seccion 1 horizontal C12.jpg          4.0        4.0   
2   Cordon17_Seccion 1 horizontal C17.jpg          4.0        4.0   
3     Cordon8_Seccion 1 horizontal C8.jpg          2.0        2.0   
4     Cordon3_Seccion 1 horizontal C3.jpg          3.0        3.0   
5   Cordon19_Seccion 1 horizontal C19.jpg          5.0        5.0   
6     Cordon9_Seccion 1 horizontal C9.jpg          2.0        2.0   
7     Cordon6_Seccion 1 horizontal C6.jpg          2.0        2.0   
8     Cordon4_Seccion 1 horizontal C4.jpg          3.0        3.0   
9   Cordon10_Seccion 1 horizontal C10.jpg          5.0        5.0   
10    Cordon5_Seccion 1 horizontal C5.jpg          5.0        5.0   
11  Cordon18_Seccion 2 horizontal C18.jpg          4.0        4.0   
12    Cordon1_Seccion 1 horizontal C1.jpg          3.0        3.0   
13  Cordon13_Seccion 1 horizontal C13.jpg          4.0        4.0   
14  Cordon16_Seccion 1 horizontal C16.jpg          4.0        4.0   
15    Cordon7_Seccion 1 horizontal C7.jpg          3.0        3.0   
16    Cordon2_Seccion 1 horizontal C2.jpg          3.0        3.0   
17  Cordon14_Seccion 1 horizontal C14.jpg          4.0        4.0   
18    Cordon1_Seccion 3 horizontal C1.jpg          3.0        3.0   
19    Cordon6_Seccion 4 horizontal C6.jpg          2.0        2.0   
20  Cordon18_Seccion 3 horizontal C18.jpg          4.0        4.0   
21  Cordon13_Seccion 3 horizontal C13.jpg          4.0        4.0   
22  Cordon19_Seccion 4 horizontal C19.jpg          5.0        5.0   
23  Cordon11_Seccion 3 horizontal C11.jpg          5.0        5.0   
24  Cordon10_Seccion 3 horizontal C10.jpg          5.0        5.0   
25    Cordon7_Seccion 2 horizontal C7.jpg          3.0        3.0   
26  Cordon16_Seccion 3 horizontal C16.jpg          4.0        4.0   
27    Cordon4_Seccion 3 horizontal C4.jpg          3.0        3.0   
28  Cordon12_Seccion 3 horizontal C12.jpg          4.0        4.0   
29    Cordon3_Seccion 3 horizontal C3.jpg          3.0        3.0   
30  Cordon17_Seccion 2 horizontal C17.jpg          4.0        4.0   
31    Cordon5_Seccion 4 horizontal C5.jpg          5.0        5.0   
32  Cordon14_Seccion 3 horizontal C14.jpg          4.0        4.0   
33    Cordon2_Seccion 3 horizontal C2.jpg          3.0        3.0   
34       Cordon9_Seccion 4 horizontal.jpg          2.0        2.0   
35    Cordon8_Seccion 5 horizontal C8.jpg          2.0        2.0   
36    Cordon8_Seccion 6 horizontal C8.jpg          2.0        2.0   
37    Cordon2_Seccion 4 horizontal C2.jpg          3.0        3.0   
38  Cordon11_Seccion 4 horizontal C11.jpg          5.0        5.0   
39  Cordon12_Seccion 5 horizontal C12.jpg          4.0        4.0   
40    Cordon6_Seccion 6 horizontal C6.jpg          2.0        2.0   
41    Cordon7_Seccion 3 horizontal C7.jpg          3.0        3.0   
42  Cordon10_Seccion 4 horizontal C10.jpg          5.0        5.0   
43  Cordon18_Seccion 4 horizontal C18.jpg          4.0        4.0   
44  Cordon16_Seccion 5 horizontal C16.jpg          4.0        4.0   
45    Cordon4_Seccion 4 horizontal C4.jpg          3.0        3.0   
46    Cordon5_Seccion 7 horizontal C5.jpg          5.0        5.0   
47    Cordon9_Seccion 6 horizontal C9.jpg          2.0        2.0   
48    Cordon1_Seccion 5 horizontal C1.jpg          3.0        3.0   
49  Cordon14_Seccion 4 horizontal C14.jpg          4.0        4.0   
50  Cordon19_Seccion 6 horizontal C19.jpg          5.0        5.0   
51  Cordon17_Seccion 3 horizontal C17.jpg          4.0        4.0   
52    Cordon3_Seccion 4 horizontal C3.jpg          3.0        3.0   
53  Cordon13_Seccion 4 horizontal C13.jpg          4.0        4.0   

    peri voltaje  voltaje  corriente  ubicacion     pixeles  mm_por_pixel  \
0            5.0      5.0        5.0          1  196.002551     65.334184   
1            4.0      4.0        4.0          1  197.002538     65.667513   
2       

In [177]:
y = df_matriz['matriz']
print(y.shape)
print(y.dtypes)

(54,)
object


In [178]:
print(y[0])

[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
